### PR TITLE
Test error computation

### PR DESCRIPTION
**Pull request by agarllo**
Error computation (norm2) is applied in all the tests.

### CODE REVIEW

**Comment by DoStrobl** [comment]
Looks good to me, but there is a typo in test_Elastic2D_4variables.py in the comment at line 316 "data-poin" instad of "data-point"

**Comment by DoStrobl** [comment]
In test_solver_problem.py, line 390 and 474 are minor mistakes in the comments as well

**Review by DoStrobl — COMMENTED** [review]
Looks good to me, but there is a typo in test_Elastic2D_4variables.py in the comment at line 316 "data-poin" instad of "data-point". 
In test_solver_problem.py in line 390 is a minor mistake in the comment as well.

**Review by aradermacher — APPROVED** [review]
please check out dominics suggestions before merging

**Comment by agarllo** [comment]
Tests update to compute the error

**Pull request merged**
